---
kind: pipeline
name: docker

steps:
- name: build
  image: docker
  environment:
    PASSWORD:
      from_secret: gitea_password
  volumes: 
  - name: sockersock
    path: /var/run
  commands: 
  - echo $PASSWORD | docker login --username gitea --password-stin
  - docker build -t 192.168.1.10:10037/gitea/oligarchy_web